#!/usr/bin/python
import subprocess
import sys

def run_command(command):
    p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    for line in p.stdout.readlines():
        print line
    retval = p.wait()

def get_backup_name(file):
    fileHandle = open(file, "r")
    lineList = fileHandle.readlines()
    fileHandle.close()
    lastLineIndex = len(lineList)-1
    if lineList[lastLineIndex].isspace():
        lastLineIndex -= 1
    words = lineList[lastLineIndex].split()
    return words[2]

if '/data/bahmni-backup/' in open('/etc/bahmni-backrest.conf').read():
    print "bahmni-backrest.conf must point all backups to /data/bahmni-backup/"
else:
    print "/etc/bahmni-backrest.conf is not updated to point the backups to /data/bahmni-backup/"
    sys.exit(1)

print "Taking backup, please wait..."
run_command("bahmni -i local backup --backup_type=all --options=all")
openmrs_backup = get_backup_name("/data/bahmni-backup/openmrs/backup_info.txt")
reports_backup = get_backup_name("/data/bahmni-backup/reports/backup_info.txt")
postgres_backup = get_backup_name("/data/bahmni-backup/postgres/backup_info.txt")
print "The openmrs backup name is: ", openmrs_backup
print "The reports backup name is: ", reports_backup
print "The postgres backup name is: ", postgres_backup
backupfile = "/data/%s-bahmni-backup.tar.gz" % openmrs_backup
tar_cmd = "cd /data;tar -czf %s bahmni-backup/*" % backupfile
run_command(tar_cmd)
print "Created backup file", backupfile

